allowBuilds:
  '@google/genai': true
  better-sqlite3: true
  esbuild: true
  lefthook: true
  lightningcss: true
  msgpackr-extract: true
  msw: true
  protobufjs: true
  sharp: true
  workerd: true
minimumReleaseAgeExclude:
  - '@shadcn/react@0.1.0'
  - shadcn@4.12.0
