packages:
  - apps/*
packageExtensions:
  streamdown:
    peerDependencies:
      '@types/react': '*'
allowBuilds:
  '@google/genai': true
  '@mongodb-js/zstd': false
  better-sqlite3: true
  core-js-pure: false
  esbuild: true
  lefthook: true
  lightningcss: true
  msgpackr-extract: true
  msw: true
  node-liblzma: false
  protobufjs: true
  sharp: true
  workerd: true
minimumReleaseAgeExclude:
  - '@shadcn/react@0.1.0'
  - shadcn@4.12.0
